In [2]:
import numpy as np

* [`numpy.argmax`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html)
    * `numpy.argmax(a, axis=None, out=None)`: 指定axis最大元素的下标
    * `axis`: （坐标）轴，By default, the index is into the flattened array
    * `out`: 如果指定，将结果存入out，out需要是合适的shape和dtype

In [20]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
np.argmax(a, axis=0)

array([2, 2, 2, 2])

In [22]:
np.argmax(a, axis=1)

array([3, 3, 3])

* [`numpy.eye`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html)
    * `numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')`
    * 

In [14]:
np.eye(5, M=2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

numpy.eye trick : 将index array转成one-hot array, [Convert array of indices to 1-hot encoded numpy array](https://stackoverflow.com/questions/29831489/convert-array-of-indices-to-1-hot-encoded-numpy-array)

In [23]:
indices = np.array([0, 1, 3])
np.eye(np.max(indices)+1)[indices]

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

numpy.eye 与 numpy.argmax trick : 将keras predict返回的概率转成predict结果，[How to get predicted values in Keras?](https://stackoverflow.com/questions/45587378/how-to-get-predicted-values-in-keras)

In [27]:
y_pred = np.array([ [ 0.57,  0.21,  0.21], [ 0.19,  0.15,  0.64], [ 0.23,  0.16,  0.6 ], [ 0.18, 0.73, 0.08] ])
np.eye(y_pred.shape[0], M=y_pred.shape[1], dtype=float)[np.argmax(y_pred, axis=1)]

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])